service: ten-day-forecast-backend

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  stage: ${opt:stage, 'test'} # stage defaults to 'test', override with --stage flag
  profile: tenDayForecastUser # profile created when configuring aws credentials

functions:
  getForecastByZipcode:
    handler: handler.main # handler lambda function
    events:
      # http GET request on /forecast will trigger the lambda function
      - httpApi:
          path: /forecast
          method: get

plugins:
  - serverless-offline
